# Generated by Django 4.2.7 on 2023-12-13 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controler', '0015_alter_dia_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='dia',
            name='hora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controler.hora'),
        ),
    ]
