# Generated by Django 4.2.7 on 2023-12-13 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controler', '0016_hora_alter_dia_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='hora',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='controler.hora'),
        ),
    ]
