# Generated by Django 4.2.7 on 2023-12-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controler', '0017_alter_dia_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dia',
            name='numero',
        ),
    ]
